In [35]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

In [36]:
df=pd.read_csv("Obesity.csv")

In [37]:
df.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [39]:
# Normalize numerical columns
scaler = MinMaxScaler()
numerical_columns = ['Age', 'Height', 'Weight', 'FCVC', 'CH2O', 'FAF', 'TUE']
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

# Encode categorical columns
encoder = LabelEncoder()
categorical_columns = ['Gender', 'family_history', 'FAVC', 'CAEC', 'SMOKE', 'SCC', 'CALC', 'MTRANS', 'Obesity']
encoded_data = {}

for col in categorical_columns:
    df[col] = encoder.fit_transform(df[col])
    encoded_data[col] = dict(zip(encoder.classes_, encoder.transform(encoder.classes_)))

# Save encoding mapping
encoded_data_df = pd.DataFrame.from_dict(encoded_data, orient='index').transpose()
encoded_data_df.to_csv('encoding_mapping.csv', index=False)

In [40]:
# Print encoding
print("Encoding mappings:")

print(encoded_data)

Encoding mappings:
{'Gender': {'Female': 0, 'Male': 1}, 'family_history': {'no': 0, 'yes': 1}, 'FAVC': {'no': 0, 'yes': 1}, 'CAEC': {'Always': 0, 'Frequently': 1, 'Sometimes': 2, 'no': 3}, 'SMOKE': {'no': 0, 'yes': 1}, 'SCC': {'no': 0, 'yes': 1}, 'CALC': {'Always': 0, 'Frequently': 1, 'Sometimes': 2, 'no': 3}, 'MTRANS': {'Automobile': 0, 'Bike': 1, 'Motorbike': 2, 'Public_Transportation': 3, 'Walking': 4}, 'Obesity': {'Insufficient_Weight': 0, 'Normal_Weight': 1, 'Obesity_Type_I': 2, 'Obesity_Type_II': 3, 'Obesity_Type_III': 4, 'Overweight_Level_I': 5, 'Overweight_Level_II': 6}}

In [41]:
df['Binary'] = df['Obesity'].map(lambda x: 0 if x == 1 else 1)

df["Binary"].unique()

array([0, 1], dtype=int64)

In [42]:
df.head()

,Gender,Age,Height,Weight,family_history,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,Obesity,Binary
0,0,0.148936,0.320755,0.186567,1,0,0.5,0.666667,2,0,0.5,0,0.000000,0.5,3,3,1,0
1,0,0.148936,0.132075,0.126866,1,0,1.0,0.666667,2,1,1.0,1,1.000000,0.0,2,3,1,0
2,1,0.191489,0.660377,0.283582,1,0,0.5,0.666667,2,0,0.5,0,0.666667,0.5,1,3,1,0
3,1,0.276596,0.660377,0.358209,0,0,1.0,0.666667,2,0,0.5,0,0.666667,0.0,1,4,5,1
4,1,0.170213,0.622642,0.379104,0,0,0.5,0.000000,2,0,0.5,0,0.000000,0.0,2,3,6,1

In [49]:
df.to_csv('final_data.csv', index=False)